### PR TITLE
include UK offbrand in countries.json

### PR DESCRIPTION
**Pull request by k9ert**
Had a talk with https://twitter.com/Bitcoinshire in Lugano at Plan B and explained him a bit more around twentyone so making that PR as a followup :-).

### CODE REVIEW

**Comment by k9ert** [comment]
@dergigi what do you think?

**Comment by k9ert** [comment]
@dennisreimann any thoughts on your side?

**Comment by dennisreimann** [comment]
Yeah, why not, it'd help others to find those meetups.

**Review by dergigi — APPROVED** [review]
Looks good to me ✅

**Pull request merged**
