### PR TITLE
feat(data): add Korea 🇰🇷

### PR DESCRIPTION
**Pull request by onebitco**
and love to list Gigi as one of our international supports on our website!

### CODE REVIEW

**Comment by dergigi** [comment]
Thanks for your contribution!

I will do my best to review the material very soon. The [twentyone.world](https://twentyone.world/) project is supposed to be a map of a network of networks, or a community of communities, and trust plays a big role in building it up. I want to make sure that—especially in the beginning—all the projects that are added are aligned with the core values of the main idea: bitcoin-only, local language, focused on local communities, run by great & trustworthy people. 

I'll do my best to get the review done by the end of the week. Thank you for your patience.

**Comment by onebitco** [comment]
Totally agree.  that's why i started [bitcoinkr.org](https://bitcoinkr.org) wanting to 
1. provide bitcoin only materials (translation and own opinions)
2. connect bitcoin hodlers.

anyway, thanks for all your work, gigi.  big fan.

**Comment by dergigi** [comment]
Are you still there, @onebitco? 

Is your project still ongoing, community intact?

**Comment by dergigi** [comment]
Are you still there, @onebitco? 

Is your project still ongoing, community intact?

**Comment by dergigi** [comment]
Last blog post is from 2022 as far as I can tell, so I'll close this PR for now.

**Pull request closed without merging**
