### PR TITLE
add Ukraine [dvadtzyatodin]

### PR DESCRIPTION
**Pull request by tetakta**
🇺🇦 dvadtzyatodin

### CODE REVIEW

**Comment by peszpesz** [comment]
Thanks for the PR @tetakta 

We have some [listing requirements](https://github.com/twentyone-world/twentyone-world.github.io/blob/main/CONTRIBUTING.md) which basically are:

Your fork speaks the [local language](https://twentyone.world/language)
Your fork has an [active beacon](https://twentyone.world/beacon) that produced signal for at least 21 weeks
Your fork has an [open group](https://twentyone.world/cyberspace) with at least 21 members
Do you fulfill all that?

**Comment by tetakta** [comment]
Yes, it's all ready to go

**Comment by tetakta** [comment]
What else do I need to do to get Bitcoin Ukraine on the map?

**Comment by peszpesz** [comment]
Nothing. I needed to get back to it. Thank you for your patience. It's processing.

**Comment by dergigi** [comment]
> Yes, it's all ready to go

@tetakta I applaud your effort, but when you say "yes" to the [questions above](https://github.com/twentyone-world/twentyone-world.github.io/pull/54#issuecomment-2003269077) we expect you to be truthful, and I'm afraid you are not.

While [your group](https://t.me/uabtchub) has 20 members, you are the only one who is active in any of the channels, so it seems like you are the only guy behind it all.

Screenshot 2024-04-04 at 16 45 34

Further, the podcast has only 3 episodes. Four if we want to be generous.

Screenshot 2024-04-04 at 16 44 25

I didn't listen to all of it, but it seems to be you talking into the mic solo. 

---

That's not the idea, as explained in [the blueprint](https://twentyone.world/blueprint#team-up). Quote:

> ### Team Up
> 
> Step zero is to [find another bitcoiner](https://twentyone.world/secrets).

@peszpesz please be more diligent when it comes to screening those who want to be added, or provide very good reasons why we want to make exceptions. CC all @twentyone-world/maintainers 

---

Again, I applaud your effort @tetakta. Please don't take this the wrong way. The idea of twentyone world is to be a blueprint and a hub for _communities_, not for people doing things solo.

**Comment by tetakta** [comment]
Anyway, thanks guys, thanks for your help. 

I'll definitely be back with a more active group and a series of new podcasts, If We Survive...

**Comment by dergigi** [comment]
Yes, please continue and reach out again in the future. Good luck!

**Comment by daic11** [comment]
> Yes, please continue and reach out again in the future. Good luck!

Hello @dergigi!

**Comment by daic11** [comment]
Hello @dergigi!

@tetakta is not alone not developing **"dvadtzyatodin"** Ukraine community.

We have translated 9 articles from the recommended list to Ukrainian - 2 of them are your authorship.
You can find the repo here https://github.com/DVADTZYATODIN/Bitcoin-Library/tree/main.

------------------------------------

Original:
Bitcoin Is Time
https://dergigi.com/2021/01/14/bitcoin-is-time/

Translation:
https://github.com/DVADTZYATODIN/Bitcoin-Library/blob/008b0804f8e34e921995373de8abbf88bcdcabc8/%D0%9B%D0%B8%D1%81%D1%82%20%D0%B2%D0%B0%D0%BC%20%D1%83%D1%81%D1%96%D0%BC%2C%20%D1%83%20%D0%BA%D0%BE%D0%B3%D0%BE%20%D0%B4%D0%BE%D1%81%D1%96%20%D0%BD%D0%B5%D0%BC%D0%B0%D1%94%20%D0%B1%D1%96%D1%82%D0%BA%D0%BE%D0%B9%D0%BD%D0%B0%20%D0%B2%D1%96%D0%B4%20%D0%94%D0%B6%D1%96%D0%B4%D0%B6%D1%96

------------------------------------

Original:
Dear Family, Dear Friends
https://dergigi.com/2020/04/27/dear-family-dear-friends/

Translation:
https://github.com/DVADTZYATODIN/Bitcoin-Library/blob/main/%D0%9B%D0%B8%D1%81%D1%82%20%D0%B2%D0%B0%D0%BC%20%D1%83%D1%81%D1%96%D0%BC%2C%20%D1%83%20%D0%BA%D0%BE%D0%B3%D0%BE%20%D0%B4%D0%BE%D1%81%D1%96%20%D0%BD%D0%B5%D0%BC%D0%B0%D1%94%20%D0%B1%D1%96%D1%82%D0%BA%D0%BE%D0%B9%D0%BD%D0%B0%20%D0%B2%D1%96%D0%B4%20%D0%94%D0%B6%D1%96%D0%B4%D0%B6%D1%96

------------------------------------

We also posted all translated articles on Nostr:
https://habla.news/p/nprofile1qyv8wumn8ghj7un9d3shjtnndehhyapwwdhkx6tpdsq3gamnwvaz7tmjv4kxz7fwv3sk6atn9e5k7qgdwaehxw309ahx7uewd3hkcqgswaehxw309ahx7um5wgh8w6twv5q3yamnwvaz7tm0venxx6rpd9hzuur4vgqzqullqax3xpg9nvp0aw77u8g2el8thzswse8nljxdtrvc2dekp754qa4v62

We posted all articles in our Ukrainian Telegram Knowledge base:
https://t.me/uabtchub/464

We posted a lot of onboarding post in our Telegram community:
https://t.me/uabtchub/1

We also moderating every day the group and have a discussions with members.
We are spending a lot of time explaining new members about btc technologies, nostr, 2nd layer btc solutions and why they should avoid altcoins. Why there are "no second best" as Michael Saylor told.

After all such discussions as a result - we create posts for newbies onboarding to make them easy to understand "what's going on". We also added a btc maxi experienced enthusiasts from other Telegram chat by the promouting our community.

Everyday we do have a new members, and we do spend a lot of time to develop the community. We already have 4 podcasts and have topics for further podcasts and will make them bi-weekly as provided in blueprint recommendations.

We are two active admins now together developing a community, which educate people about Bitcoin in Ukraine by their native language.

------------------------------------

Checklist
[Find another bitcoiner](https://twentyone.world/fork#the-trick)
Don’t try to do it alone.
[Fork the name](https://twentyone.world/fork#the-name) (optional)
Translate “twentyone” into your local language.
[Fork the logo](https://twentyone.world/logo) (optional)
Feel free to be creative!
[Create a beacon](https://twentyone.world/fork#the-concept)
A [podcast](https://twentyone.world/podcast) is easiest and works best.
[Create a group](https://twentyone.world/fork#the-trick)
Telegram works well, but any place where people can meet and exchange ideas works.
[Translate content](https://twentyone.world/language#translations)
We have a list of articles to get you started.
[Be consistent](https://twentyone.world/fork#the-trick)
This is key. Whatever you do, stick with it for at least 21 weeks.
 
Your fork speaks the [local language](https://twentyone.world/language)
Your fork has an [active beacon](https://twentyone.world/beacon) that produced signal for at least 21 weeks
Your fork has an [open group](https://twentyone.world/cyberspace) with at least 21 members

------------------------------------

#### I'd also like to point out that we've met all the guidelines and requirements to be in compliance with the twenty-one world community.

We invest our time every day, and the next necessary step for us is to have our work recognized. We are a community with active 28 participants in our Telegram chat in their native Ukrainian language.

Our Telegram community with 28 member. https://t.me/uabtchub
Our podcast (beacon) which is broadcasting to 31 members. https://pod.link/1721796452

I ask you to consider all of the above and appreciate our hard work by accepting us into the TwentyOne World community as representatives from Ukraine. We want to promote the idea of bitcoin in our country in the long term. Thank you!

photo_2024-05-09_16-03-55

Screenshot 2024-05-09 at 16 26 44

**Pull request merged**
