### PR TITLE
chore(data): add Dvadsaťjeden (Slovakia)

### PR DESCRIPTION
**Pull request by hynek-jina**

### CODE REVIEW

**Comment by dergigi** [comment]
Nice! What's the status in terms of group size, episodes, etc?

https://github.com/twentyone-world/twentyone-world.github.io/blob/main/CONTRIBUTING.md

**Comment by hynek-jina** [comment]
Czechia 
- 272 members, and 16 communities
- 10 articles ready for blog
- Podcast - only discussions so far

Slovakia - 15 members

**Comment by dergigi** [comment]
Nice! 

Make sure to pump out that [constant signal](https://twentyone.world/beacon), as it is one of the most essential aspects of the concept.

Good luck & congratulations on getting that far already! 🧡

**Review by dergigi — APPROVED** [review]
Looks good to me ✅

**Comment by hynek-jina** [comment]
Thank you.. 
Yes.. the signal is a bit tricky. We have already at least 3 great bitcoin podcasts in Czechia. And I'm not sure it's viable to create another. Currently we are trying to find some owner for this idea.

**Pull request merged**
