### PR TITLE
Add Bitcoin Paraguay community 🇵🇾

### PR DESCRIPTION
**Pull request by kotasjan**
Add Bitcoin Paraguay community page ( https://bitcoinparaguay.org/ ).

### CODE REVIEW

**Comment by dennisreimann** [comment]
The page and blog seem pretty empty and there are no upcoming events. Please ensure you fulfill the basic [listing requirements](https://github.com/twentyone-world/twentyone-world.github.io/blob/main/CONTRIBUTING.md)::

* Your fork has an [active beacon](https://twentyone.world/beacon) that produced signal for at least 21 weeks
* Your fork has an [open group](https://twentyone.world/cyberspace) with at least 21 members

**Comment by kotasjan** [comment]
Our community has existed for more than seven months, and we currently have 120 members. We just didn't have a website running for a couple of months. Now everything is up and running, including our socials. You can recheck it.

**Comment by dergigi** [comment]
Blog has [recent updates](https://bitcoinparaguay.org/blog/), [good vision](https://bitcoinparaguay.org/2024/07/04/vision-y-estructura-de-bitcoin-paraguay/), and an [active npub](https://njump.me/npub1l57mdhhlkuulspszd6qarjxennpytglns6kth2agmjvrwyx8aqdqgj645x).

I'll merge this in the next ~24h or so unless someone stops me with a good reason.

**Comment by dergigi** [comment]
@kotasjan do I understand this correctly, that there is [no open group](https://twentyone.world/cyberspace), but you have local communities that each have their own [WhatsApp group](https://bitcoinparaguay.org/comunidades/)? 

How does it work? Are these groups open and anyone can join? Do you have an open group for Bitcoin Paraguay?

**Comment by kotasjan** [comment]
@dergigi We had an open WhatsApp community for a long time, but we had to change it because many people were just joining the group without ever showing up at our events - often with anonymous identities, so we had no idea who they were. We also have to consider the safety of our members. Even though Paraguay is quite a safe country (at least from a LATAM perspective), the potential risk of an attack on our members is much higher than in Europe, for example. We had an incident where one of the anonymous accounts was seriously threatening one of our admins, which served as a wake-up call for us.

After many discussions, we decided to raise the requirements for people to join our communities. People can still join and are welcome to be part of our communities, but only during our regular local community meetups. This way, the local admins know who is part of their community, and it adds one more barrier for bad actors to enter our groups. Since implementing this change, our communities have become much healthier, with more activity and participation, and people also value their membership much more because it is not taken for granted.

If you want, we can have a call one day, and I can explain the whole concept and the lessons we've learned during the last couple of months.

**Comment by dergigi** [comment]
Thanks for the in-depth explanation. 

> Since implementing this change, our communities have become much healthier, with more activity and participation, and people also value their membership much more because it is not taken for granted.

I'm glad that's working for you. Seems like a very sensible approach.

Keep up the great work! 💪🧡

**Comment by kotasjan** [comment]
> Thanks for the in-depth explanation.
> 
> > Since implementing this change, our communities have become much healthier, with more activity and participation, and people also value their membership much more because it is not taken for granted.
> 
> I'm glad that's working for you. Seems like a very sensible approach.
> 
> Keep up the great work! 💪🧡

Awesome! Thank you! 🙏

**Pull request merged**
