### PR TITLE
Add Polish fork

### PR DESCRIPTION
**Pull request by jesterhodl**
Adding Logo in PNG format
Updating countries.json with name and link to our website.
The website leads to our existing Telegram Community of Bitcoin maxis as well as fledgling twitter account.

### CODE REVIEW

**Comment by jesterhodl** [comment]
Hey @dergigi is this good to commit?

**Comment by dergigi** [comment]
@jesterhodl it says "This site is private." - any reason for this? I'd rather prefer public communities to be honest.

**Comment by jesterhodl** [comment]
Of course, it's made public now!
Background is that I first made Notion page.
In the meantime, I moved us to a Ghost and it was only temporarily private during setup.

**Review by dergigi — APPROVED** [review]
Apologies for the massive delay on this @jesterhodl 

Looks good to me ✅

**Pull request merged**
